// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfddlK9cScSGflS242S0w1ZnkfuVJLSTY',
    appId: '1:720954728630:web:1abec7b3f1487c1d258617',
    messagingSenderId: '720954728630',
    projectId: 'chatapp-dfdeb',
    authDomain: 'chatapp-dfdeb.firebaseapp.com',
    storageBucket: 'chatapp-dfdeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLp3bHen4wtEowgIdh8dmB62EJ-g1QWIA',
    appId: '1:720954728630:android:fc6f0869758867b3258617',
    messagingSenderId: '720954728630',
    projectId: 'chatapp-dfdeb',
    storageBucket: 'chatapp-dfdeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxme-hUFebJCU2QO55ZVaVsdcqxOi8fV0',
    appId: '1:720954728630:ios:1e799796176c560b258617',
    messagingSenderId: '720954728630',
    projectId: 'chatapp-dfdeb',
    storageBucket: 'chatapp-dfdeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxme-hUFebJCU2QO55ZVaVsdcqxOi8fV0',
    appId: '1:720954728630:ios:1e799796176c560b258617',
    messagingSenderId: '720954728630',
    projectId: 'chatapp-dfdeb',
    storageBucket: 'chatapp-dfdeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfddlK9cScSGflS242S0w1ZnkfuVJLSTY',
    appId: '1:720954728630:web:5ed32f5e1a972274258617',
    messagingSenderId: '720954728630',
    projectId: 'chatapp-dfdeb',
    authDomain: 'chatapp-dfdeb.firebaseapp.com',
    storageBucket: 'chatapp-dfdeb.firebasestorage.app',
  );
}
